company                                      = "company"
project                                      = "workshop"
region                                       = "eu-west-2"
name					     = "Owen"
environment				     = "development"
