company                                      = "company"
project                                      = "workshop"
region                                       = "eu-west-2"
name					     = "Owen"
version-demo 	                             = "2022092803"
environment				     = "development"
